INSERT INTO INGREDIENT (NAME, UNIT) VALUES ('Woda', 'MILILITER')
INSERT INTO INGREDIENT (NAME, UNIT) VALUES ('Maka', 'GRAM')
INSERT INTO INGREDIENT (NAME, UNIT) VALUES ('Cukier', 'GRAM')
INSERT INTO INGREDIENT (NAME, UNIT) VALUES ('Sol', 'GRAM')